{{- if and .Values.mastodon.libretranslate.enabled (not .Values.mastodon.libretranslate.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.fullname" . }}-libretranslate
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.mastodon.libretranslate.apiKey | b64enc }}
  endpoint: {{ .Values.mastodon.libretranslate.endpoint | b64enc }}
{{- end }}
